name = "your-project-name"
type = "javascript"

[build]
command = "npm run build"
directory = "dist"

[dev]
command = "npm run dev"
port = 8787

[[routes]]
pattern = "your-domain.com/unlock/*"
zone_id = "your-zone-id"
script = "your-project-name"

[[routes]]
pattern = "*/unlock/*"
zone_id = "your-zone-id"
script = "your-project-name"
